### ISSUE TITLE
Gradle project refresh failed

### ISSUE THREAD

**Issue by ghost** [michal-luszczuk/tomorrow-mvp#1]
I get this error when opening:

Error:Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@2852cc7e.

**Comment by michal-luszczuk** [comment]
Should be fixed with [https://github.com/michal-luszczuk/tomorrow-mvp/commit/ad271d6b3417acce91f956a477b4e12a65f77582](https://github.com/michal-luszczuk/tomorrow-mvp/commit/ad271d6b3417acce91f956a477b4e12a65f77582)
